#!/bin/bash
#SBATCH --job-name=align
#SBATCH -n 1
#SBATCH -N 1
#SBATCH -c 8
#SBATCH --mem=20G
#SBATCH --partition=general
#SBATCH --qos=general
#SBATCH --mail-type=ALL
#SBATCH --mail-user=amy.lafountain@uconn.edu
#SBATCH -o %x_%j.out
#SBATCH -e %x_%j.err

echo `hostname`

##################################################################################
# Aligning to Genome with HiSat2, followed by sorting, compression and indexing
##################################################################################
module load hisat2/2.2.1
module load samtools/1.10

hisat2 -p 8 --dta -x ../hisat2_genome/MVBL -1 ../results/trimming/HY5A_1_1pair.trimmed.fastq.gz -2 ../results/trimming/HY5A_1_2pair.trimmed.fastq.gz | \
	samtools view -@ 8 -S -h -u - | \
	samtools sort -@ 8 -T HY5A_1 - >HY5A_1.bam

hisat2 -p 8 --dta -x ../hisat2_genome/MVBL -1 ../results/trimming/HY5A_2_1pair.trimmed.fastq.gz -2 ../results/trimming/HY5A_2_2pair.trimmed.fastq.gz | \
	samtools view -@ 8 -S -h -u - | \
	samtools sort -@ 8 -T HY5A_2 - >HY5A_2.bam

hisat2 -p 8 --dta -x ../hisat2_genome/MVBL -1 ../results/trimming/HY5A_3_1pair.trimmed.fastq.gz -2 ../results/trimming/HY5A_3_2pair.trimmed.fastq.gz | \
	samtools view -@ 8 -S -h -u - | \
	samtools sort -@ 8 -T HY5A_3 - >HY5A_3.bam

hisat2 -p 8 --dta -x ../hisat2_genome/MVBL -1 ../results/trimming/HY5A_4_1pair.trimmed.fastq.gz -2 ../results/trimming/HY5A_4_2pair.trimmed.fastq.gz | \
	samtools view -@ 8 -S -h -u - | \
	samtools sort -@ 8 -T HY5A_4 - >HY5A_4.bam


# index bam files
samtools index HY5A_1.bam HY5A_1.bai
samtools index HY5A_2.bam HY5A_2.bai
samtools index HY5A_3.bam HY5A_3.bai
samtools index HY5A_4.bam HY5A_4.bai
