#!/bin/bash 
#SBATCH --job-name=compress
#SBATCH -n 1
#SBATCH -N 1
#SBATCH -c 4
#SBATCH --mem=10G
#SBATCH --qos=general
#SBATCH --partition=general
#SBATCH --mail-user=amy.lafountain@uconn.edu
#SBATCH --mail-type=END
#SBATCH -o %x_%j.out
#SBATCH -e %x_%j.err

hostname
date

# load software
module load samtools

# set directory for input and output files
DIR=../alignments

samtools view -bhS $DIR/proximal_1.sam >$DIR/proximal_1.bam
samtools view -bhS $DIR/proximal_2.sam >$DIR/proximal_2.bam
samtools view -bhS $DIR/proximal_3.sam >$DIR/proximal_3.bam
samtools view -bhS $DIR/proximal_4.sam >$DIR/proximal_4.bam
samtools view -bhS $DIR/stripe_1.sam >$DIR/stripe_1.bam
samtools view -bhS $DIR/stripe_2.sam >$DIR/stripe_2.bam
samtools view -bhS $DIR/stripe_3.sam >$DIR/stripe_3.bam
samtools view -bhS $DIR/stripe_4.sam >$DIR/stripe_4.bam
samtools view -bhS $DIR/distal_1.sam >$DIR/distal_1.bam
samtools view -bhS $DIR/distal_2.sam >$DIR/distal_2.bam
samtools view -bhS $DIR/distal_3.sam >$DIR/distal_3.bam
samtools view -bhS $DIR/distal_4.sam >$DIR/distal_4.bam
