#!/bin/bash
#SBATCH --job-name=salmon
#SBATCH -n 1
#SBATCH -N 1
#SBATCH -c 8
#SBATCH --mem=20G
#SBATCH --partition=general
#SBATCH --qos=general
#SBATCH --mail-type=ALL
#SBATCH --mail-user=amy.lafountain@uconn.edu
#SBATCH -o %x_%j.out
#SBATCH -e %x_%j.err

# TODO: uncomment me for running on server
module load salmon

for fn in ../results/trimming/*_*_*.fastq.gz
do
    echo Processing: $fn

    IFS="_" read -a strarr <<< $fn
    # THIS IS JUST SHOWING HOW TO ACCESS PIECES OF THE ARRAY
    #echo "${strarr[0]}"
    #echo "${strarr[1]}"
    #echo "${strarr[2]}"
    printf "\n"

    # THIS SHOULD CONTROL WHETHER YOU AVOID PROCESSING FILE 2
    if [[ ! ${strarr[2]::1} -eq 1 ]]
    then
        echo "It's not the first file: ${fn} "
        continue
    fi

    # TODO: uncomment me for running on server
    salmon quant -i ../salmon_index/MvBLg_v2.0_index/ -l A \
            -1 "${strarr[0]}_${strarr[1]}_1pair.trimmed.fastq.gz" \
            -2 "${strarr[0]}_${strarr[1]}_2pair.trimmed.fastq.gz" \
            -p 8 --validateMappings -o quants/${strarr[0]}_${strarr[1]}_quant
done 

#-i tells salmon where to find the index; -l A tells salmon to automatically determine the library type; -p 8 tells salmon to use 8 threads; -o specifies the output directory
#these are the base options for salmon-there are many more options available in the salmon documentation
#quoted from salmon guide- you’ll see a simple TSV format file listing the name (Name) of each transcript, its length (Length), effective length (EffectiveLength), and its abundance in terms of Transcripts Per Million (TPM) and estimated number of reads (NumReads) originating from this transcript.
