#!/bin/bash
#add the slurm header! make sure number of threads is 8. 

for i in *pair.trimmed.fastq.gz
do
   prefix=$(basename $i for *pair.trimmed.fastq.gz)
   salmon quant -i ../salmon_index/MvBLg_v2.0_index/ --libType A \
          -1 ${prefix}_1pair.trimmed.fastq.gz -2 ${prefix}_2pair.trimmed -o quant/${prefix};
done


#-i tells salmon where to find the index; -l A tells salmon to automatically determine the library type; -p 8 tells salmon to use 8 threads; -o specifies the output directory
#these are the base options for salmon-there are many more options available in the salmon documentation
#quoted from salmon guide- you’ll see a simple TSV format file listing the name (Name) of each transcript, its length (Length), effective length (EffectiveLength), and its abundance in terms of Transcripts Per Million (TPM) and estimated number of reads (NumReads) originating from this transcript.
