#!/bin/bash
#SBATCH --job-name=hisat2_index
#SBATCH -n 1
#SBATCH -N 1
#SBATCH -c 16
#SBATCH --mem=20G
#SBATCH --partition=general
#SBATCH --qos=general
#SBATCH --mail-type=ALL
#SBATCH --mail-user=amy.lafountain@uconn.edu
#SBATCH -o %x_%j.out
#SBATCH -e %x_%j.err

wget http://mimubase.org/FTP/Genomes/MvBLg_v2.0/MvBLg_v2.0.codingseq.fa

module load salmon

salmon index -t MvBLg_v2.0.codingseq.fa -i MvBLg_v2.0_index
