#!/bin/bash
#SBATCH --job-name=trimmomatic
#SBATCH -c 12
#SBATCH -n 1
#SBATCH -N 1
#SBATCH -a 0-3
#SBATCH --partition=general
#SBATCH --qos=general
#SBATCH --mail-type=END
#SBATCH --mem=16G
#SBATCH --mail-user=firstname.lastname@uconn.edu
#SBATCH -o %x_%A_%a.out
#SBATCH -e %x_%A_%a.err

# the -a flag reflects the number of samples in your array and needs to be adjusted each time--the first sample is 0, second sample is 1, and so on.
# the %x_%A_%a is being used to specify the names of the .out and .err files because this is an array, and each sample will generate a unique pair of files.

module load Trimmomatic/0.39
INDIR=/path/to/raw/reads/directory

F_reads=($INDIR/sampleA_1.fq.gz $INDIR/sampleB_1.fq.gz $INDIR/sampleC_1.fq.gz $INDIR/sampleD_1.fq.gz)
        
# can add more files, just seperate them by one space]

R_reads=($INDIR/sampleA_2.fq.gz $INDIR/sampleB_2.fq.gz $INDIR/sampleC_2.fq.gz $INDIR/sampleD_2.fq.gz)
       
# can add more files, just sperate them by one space. Note that the order of these R files must correspond to the F files above!!!

output=(sampleA sampleB sampleC sampleD)

#set up the directory where you want the trimmed reads to be stored, and change to that directory

mkdir /path/to/where/the/trimmed/reads/should/go
cd /path/to/where/the/trimmed/reads/should/go

# use ${F_reads[$SLURM_ARRAY_TASK_ID]} and ${R_reads[$SLURM_ARRAY_TASK_ID]} in your command to recall reads files, for example:

java -jar $Trimmomatic PE -threads 8 -phred33 -validatePairs ${F_reads[$SLURM_ARRAY_TASK_ID]} ${R_reads[$SLURM_ARRAY_TASK_ID]}\
             ${output[$SLURM_ARRAY_TASK_ID]}_1pair.trimmed.fastq.gz ${output[$SLURM_ARRAY_TASK_ID]}_1un.trimmed.fastq.gz ${output[$SLURM_ARRAY_TASK_ID]}_2pair.trimmed.fastq.gz ${output[$SLURM_ARRAY_TASK_ID]}_2un.trimmed.fastq.gz\
		ILLUMINACLIP:/isg/shared/apps/Trimmomatic/0.36/adapters/TruSeq3-PE-2.fa:2:30:10 \
               	LEADING:5\
		TRAILING:5\
		SLIDINGWINDOW:4:20\
		MINLEN:45\
