#!/bin/bash 
#SBATCH --job-name=fastqc
#SBATCH -n 1
#SBATCH -N 1
#SBATCH -c 6
#SBATCH --mem=32G
#SBATCH --qos=general
#SBATCH --partition=general
#SBATCH --mail-user=firstname.lastname@uconn.edu
#SBATCH --mail-type=END
#SBATCH -o %x_%j.out
#SBATCH -e %x_%j.err


hostname
date

# load software
module load fastqc

# create output directory
OUTDIR=/path/to/where/you/want/files/to/go
mkdir -p $OUTDIR

# run fastqc. "*fq" tells it to run on all fastq files in directory
find /raw/data/directory/ -name '*.gz' -exec fastqc -t 6 -o $OUTDIR {} \;

date
