#!/bin/bash
#SBATCH --job-name=htseq_count
#SBATCH -n 1
#SBATCH -N 1
#SBATCH -c 1
#SBATCH --mem=20G
#SBATCH --partition=general
#SBATCH --qos=general
#SBATCH --mail-type=ALL
#SBATCH --mail-user=amy.lafountain@uconn.edu
#SBATCH -o %x_%j.out
#SBATCH -e %x_%j.err

echo `hostname`

###Download the GFF3 file from Mimubase using wget

#################################################################
# Generate Counts 
#################################################################
module load htseq

htseq-count -s no -r pos -f bam ../alignments/distal_1_sort.bam ../genome/MvBLg_v2.0.gtf > ../results/counts/distal_1.counts
htseq-count -s no -r pos -f bam ../alignments/distal_2_sort.bam ../genome/MvBLg_v2.0.gtf > ../results/counts/distal_2.counts
htseq-count -s no -r pos -f bam ../alignments/distal_3_sort.bam ../genome/MvBLg_v2.0.gtf > ../results/counts/distal_3.counts
htseq-count -s no -r pos -f bam ../alignments/distal_4_sort.bam ../genome/MvBLg_v2.0.gtf > ../results/counts/distal_4.counts
htseq-count -s no -r pos -f bam ../alignments/stripe_1_sort.bam ../genome/MvBLg_v2.0.gtf > ../results/counts/stripe_1.counts
htseq-count -s no -r pos -f bam ../alignments/stripe_2_sort.bam ../genome/MvBLg_v2.0.gtf > ../results/counts/stripe_2.counts
htseq-count -s no -r pos -f bam ../alignments/stripe_3_sort.bam ../genome/MvBLg_v2.0.gtf > ../results/counts/stripe_3.counts
htseq-count -s no -r pos -f bam ../alignments/stripe_4_sort.bam ../genome/MvBLg_v2.0.gtf > ../results/counts/stripe_4.counts
htseq-count -s no -r pos -f bam ../alignments/proximal_1_sort.bam ../genome/MvBLg_v2.0.gtf > ../results/counts/proximal_1.counts
htseq-count -s no -r pos -f bam ../alignments/proximal_2_sort.bam ../genome/MvBLg_v2.0.gtf > ../results/counts/proximal_2.counts
htseq-count -s no -r pos -f bam ../alignments/proximal_3_sort.bam ../genome/MvBLg_v2.0.gtf > ../results/counts/proximal_3.counts
htseq-count -s no -r pos -f bam ../alignments/proximal_4_sort.bam ../genome/MvBLg_v2.0.gtf > ../results/counts/proximal_4.counts

#-s indicates that our RNAseq library is unstranded; -r indicates that the BAM file has been sorted; -f indicates the file format
#can use gtf or gff3 format, but htseq expects the gtf format and gff3 will give an error about gene IDs
