#!/bin/bash
#SBATCH --job-name=Mpar_htseq_count
#SBATCH -n 1
#SBATCH -N 1
#SBATCH -c 1
#SBATCH --mem=20G
#SBATCH --partition=general
#SBATCH --qos=general
#SBATCH --mail-type=ALL
#SBATCH --mail-user=amy.lafountain@uconn.edu
#SBATCH -o %x_%j.out
#SBATCH -e %x_%j.err

echo `hostname`

#################################################################
# Generate Counts 
#################################################################
module load htseq

GTF=../genome/Mparg_v2.0.gtf

INDIR=../RNAseq/202402_tissues_results/Mpar_hisat2_alignments
OUTDIR=../RNAseq/202402_tissues_results/Mpar_htseq_counts
mkdir -p $OUTDIR

htseq-count -s no -r pos -f bam $INDIR/Mp_calyx.bam $GTF > $OUTDIR/Mp_calyx.counts
htseq-count -s no -r pos -f bam $INDIR/Mp_corolla.bam $GTF > $OUTDIR/Mp_corolla.counts
htseq-count -s no -r pos -f bam $INDIR/Mp_pistil.bam $GTF > $OUTDIR/Mp_pistil.counts
htseq-count -s no -r pos -f bam $INDIR/Mp_stamen.bam $GTF > $OUTDIR/Mp_stamen.counts

#-s indicates that our RNAseq library is unstranded; -r indicates that the BAM file has been sorted; -f indicates the file format
#can use gtf or gff3 format, but htseq expects the gtf format and gff3 will give an error about gene IDs
