#!/bin/bash
#SBATCH --job-name=hisat_alignment
#SBATCH -n 1
#SBATCH -N 1
#SBATCH -c 8
#SBATCH --mem=20G
#SBATCH --partition=xeon
#SBATCH --qos=general
#SBATCH --mail-type=ALL
#SBATCH --mail-user=firstname.lastname@uconn.edu
#SBATCH -o %x_%j.out
#SBATCH -e %x_%j.err

echo `hostname`

##################################################################################
# Aligning to Genome with HiSat2, followed by sorting, compression and indexing
##################################################################################
module load hisat2/2.2.1
module load samtools/1.10

INDEX=../genome/Mpar_hisat2_index/Mpar
INDIR=../path/to/trimmed/reads
OUTDIR=../path/to/hisat2_alignments
mkdir -p $OUTDIR

hisat2 -p 8 --dta -x $INDEX -1 $INDIR/Mp_cal5_1pair.trimmed.fastq.gz -2 $INDIR/Mp_cal5_2pair.trimmed.fastq.gz | \
	samtools view -@ 8 -S -h -u - | \
	samtools sort -@ 8 -T Mp_calyx - >$OUTDIR/Mp_calyx.bam

hisat2 -p 8 --dta -x $INDEX -1 $INDIR/Mp_cor6_1pair.trimmed.fastq.gz -2 $INDIR/Mp_cor6_2pair.trimmed.fastq.gz | \
	samtools view -@ 8 -S -h -u - | \
	samtools sort -@ 8 -T Mp_corolla - >$OUTDIR/Mp_corolla.bam

hisat2 -p 8 --dta -x $INDEX -1 $INDIR/Mp_pis7_1pair.trimmed.fastq.gz -2 $INDIR/Mp_pis7_2pair.trimmed.fastq.gz | \
	samtools view -@ 8 -S -h -u - | \
	samtools sort -@ 8 -T Mp_pistil - >$OUTDIR/Mp_pistil.bam

hisat2 -p 8 --dta -x $INDEX -1 $INDIR/Mp_sta8_1pair.trimmed.fastq.gz -2 $INDIR/Mp_sta8_2pair.trimmed.fastq.gz | \
	samtools view -@ 8 -S -h -u - | \
	samtools sort -@ 8 -T Mp_stamen - >$OUTDIR/Mp_stamen.bam

#samtools view is telling the samtools program to convert the SAM file (that was produced by hisat) into the compressed BAM format
#the flags are as follows: -S indicates that the input file is in SAM format, -h indicates that the header of the input file should be written into the output, -u indicates that the BAM file should be written in uncompressed format 
#samtools sort is telling the samtools program to sort and compress the bam files. the -T flag is telling the program to create a temporary file that will be deleted upon completion.

# lastly we need to index bam files
samtools index $OUTDIR/Mp_calyx.bam 
samtools index $OUTDIR/Mp_corolla.bam 
samtools index $OUTDIR/Mp_pistil.bam 
samtools index $OUTDIR/Mp_stamen.bam
