#!/bin/bash
#SBATCH --job-name=htseq_count
#SBATCH -n 1
#SBATCH -N 1
#SBATCH -c 1
#SBATCH --mem=20G
#SBATCH --partition=general
#SBATCH --qos=general
#SBATCH --mail-type=ALL
#SBATCH --mail-user=firstname.lastname@uconn.edu
#SBATCH -o %x_%j.out
#SBATCH -e %x_%j.err

echo `hostname`

# Generate Counts 

module load htseq

GTF=../genome/Mparg_v2.0.gtf

INDIR=../path/to/hisat2_alignments
OUTDIR=../path/to/Mpar_htseq_counts
mkdir -p $OUTDIR

htseq-count -s no -r pos -f bam $INDIR/SampleA.bam $GTF > $OUTDIR/SampleA.counts
htseq-count -s no -r pos -f bam $INDIR/SampleB.bam $GTF > $OUTDIR/SampleB.counts
htseq-count -s no -r pos -f bam $INDIR/SampleC.bam $GTF > $OUTDIR/SampleC.counts
htseq-count -s no -r pos -f bam $INDIR/SampleD.bam $GTF > $OUTDIR/SampleD.counts

#-s indicates that our RNAseq library is unstranded; -r indicates that the BAM file has been sorted; -f indicates the file format
#can use gtf or gff3 format, but htseq expects the gtf format and gff3 will give an error about gene IDs
